// Loads the `wonton-wasm` package (generated by `npm run wasm:build` — see package.json — into
// `src/wasm-pkg/`, gitignored, regenerated from `../crates/wasm`) and re-exports it alongside
// small base64/bytes helpers the browser doesn't provide natively (no `Buffer` here).
//
// This module is the ONLY place that imports `wasm-pkg` directly — everything else in the
// dashboard goes through the typed helpers below, so there's exactly one seam to update if the
// wasm crate's API ever changes shape.

// Generated at build time by `npm run wasm:build` (both `npm run dev` and `npm run build` run it
// first — see package.json) — not present in a fresh checkout until then; see the README.
import init, { unlock_identity, verify_commit, parse_tree, Argon2ParamsInput, type IdentityHandle, type DekHandle } from "./wasm-pkg/wonton_wasm.js";

let ready: Promise<void> | null = null;

/** Must be called (and awaited) once before any other function in this module. Idempotent. */
export function ensureWasmReady(): Promise<void> {
  if (!ready) ready = init().then(() => undefined);
  return ready!;
}

export function bytesToBase64(bytes: ArrayBuffer): string {
  let binary = "";
  const view = new Uint8Array(bytes);
  for (let i = 0; i < view.length; i++) binary += String.fromCharCode(view[i]);
  return btoa(binary);
}

export function utf8ToBase64(s: string): string {
  return bytesToBase64(new TextEncoder().encode(s).buffer);
}

export {
  unlock_identity as unlockIdentity,
  verify_commit as verifyCommit,
  parse_tree as parseTree,
  Argon2ParamsInput,
  type IdentityHandle,
  type DekHandle,
};
